### ISSUE TITLE
Add eslint to project

### ISSUE THREAD

**Issue by OdunayoOkebunmi** [she-code-africa/WOSCA-book-gallery#2]
**Why this is important**
ESLint is the required linter for the project. It'll help check for style violations and flag them.

**Useful links**
https://www.npmjs.com/package/eslint-config-airbnb
https://www.npmjs.com/package/eslint

**Comment by Omotola28** [comment]
Currently working on this issue

**Comment by mazma1** [comment]
Resolved.
