### ISSUE TITLE
Users should be able login on WOSCA-book-gallery - Login form UI

### ISSUE THREAD

**Issue by OdunayoOkebunmi** [she-code-africa/WOSCA-book-gallery#7]
To be able to use the application and access authenticated routes, registered users should be able to log in using the login form. This issue only builds out the form, no API required.

**Comment by mazma1** [comment]
**A small change to the mockup:**
1. Users should be able to log in with their username **OR** email address

Mock up guide:
![login mockup](https://user-images.githubusercontent.com/15054956/87714663-b62f3380-c771-11ea-8a9b-2f117a379793.png)

**Comment by sandygudie** [comment]
Awesome
